default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: <%= ENV.fetch("BOOKLY_DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("BOOKLY_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("BOOKLY_DATABASE_PASSWORD") %>
  database: <%= ENV.fetch("BOOKLY_DATABASE_DEVELOPMENT") %>

test:
  <<: *default
  host: <%= ENV.fetch("BOOKLY_DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("BOOKLY_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("BOOKLY_DATABASE_PASSWORD") %>
  database: <%= ENV.fetch("BOOKLY_DATABASE_TEST") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
