default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    <<: *default
    host: <%= ENV["BOOKLY_DATABASE_HOST"] || "localhost" %>
    username: <%= ENV["BOOKLY_DATABASE_USERNAME"] %>
    password: <%= ENV["BOOKLY_DATABASE_PASSWORD"] %>
    database: <%= ENV["BOOKLY_DATABASE_DEVELOPMENT"] %>

  queue:
    <<: *default
    host: <%= ENV["BOOKLY_DATABASE_HOST"] || "localhost" %>
    username: <%= ENV["BOOKLY_DATABASE_USERNAME"] %>
    password: <%= ENV["BOOKLY_DATABASE_PASSWORD"] %>
    database: <%= ENV["BOOKLY_DATABASE_DEVELOPMENT"] %>

test:
  primary:
    <<: *default
    host: <%= ENV["BOOKLY_DATABASE_HOST"] || "localhost" %>
    username: <%= ENV["BOOKLY_DATABASE_USERNAME"] %>
    password: <%= ENV["BOOKLY_DATABASE_PASSWORD"] %>
    database: <%= ENV["BOOKLY_DATABASE_TEST"] %>

  queue:
    <<: *default
    host: <%= ENV["BOOKLY_DATABASE_HOST"] || "localhost" %>
    username: <%= ENV["BOOKLY_DATABASE_USERNAME"] %>
    password: <%= ENV["BOOKLY_DATABASE_PASSWORD"] %>
    database: <%= ENV["BOOKLY_DATABASE_TEST"] %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
